#!/usr/bin/env bash

DIR=$(realpath $(dirname $0))
cd $DIR

rm -rf ./app/rc_*.py

for f in ./res/*.qrc; do
    FILE_NAME=$(basename -s .qrc $f)
    echo "[Compiling]: ${FILE_NAME}.qrc ---> ui_${FILE_NAME}.py"
    pyside2-rcc $f -o "./app/rc_${FILE_NAME}.py"
done

