name: Build Linux (x64)
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python -m pip install requests
      - run: python -m pip install requests
      - run: python -m pip install setuptools wheel
      - run: python -m pip install -U -r requirements.txt
      - working-directory: ./packaging
        run: ./linux_source.sh --run yes --tar no --deb no --python python
      - uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./packaging/dist/*
          retention-days: 1
